// <auto-generated />
using System;
using LinkYourLaundry;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinkYourLaundry.Migrations
{
    [DbContext(typeof(LaundryDbContext))]
    [Migration("20181115202841_AddUniqueIndices")]
    partial class AddUniqueIndices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LinkYourLaundry.Models.ActiveLaundry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed");

                    b.Property<DateTime>("DryStartTime");

                    b.Property<int>("LaundryTemplateId");

                    b.Property<int>("UserId");

                    b.Property<DateTime>("WashStartTime");

                    b.HasKey("Id");

                    b.HasIndex("LaundryTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("ActiveLaundries");
                });

            modelBuilder.Entity("LinkYourLaundry.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("GroupOwnerId");

                    b.Property<int>("InvitedUserId");

                    b.HasKey("Id");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("GroupOwnerId", "InvitedUserId")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("LinkYourLaundry.Models.LaundryTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Detergent");

                    b.Property<string>("DryCycle");

                    b.Property<TimeSpan>("DryDuration");

                    b.Property<string>("Name");

                    b.Property<int>("UserId");

                    b.Property<string>("WashCycle");

                    b.Property<TimeSpan>("WashDuration");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "UserId")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("LaundryTemplates");
                });

            modelBuilder.Entity("LinkYourLaundry.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LinkYourLaundry.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<int?>("GroupOwnerId");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("GroupOwnerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LinkYourLaundry.Models.ActiveLaundry", b =>
                {
                    b.HasOne("LinkYourLaundry.Models.LaundryTemplate", "LaundryTemplate")
                        .WithMany("ActiveLaundries")
                        .HasForeignKey("LaundryTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LinkYourLaundry.Models.User", "User")
                        .WithMany("ActiveLaundries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LinkYourLaundry.Models.Invitation", b =>
                {
                    b.HasOne("LinkYourLaundry.Models.User", "GroupOwner")
                        .WithMany("PendingActiveInvitations")
                        .HasForeignKey("GroupOwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LinkYourLaundry.Models.User", "InvitedUser")
                        .WithMany("PendingPassiveInvitations")
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LinkYourLaundry.Models.LaundryTemplate", b =>
                {
                    b.HasOne("LinkYourLaundry.Models.User", "User")
                        .WithMany("LaundryTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LinkYourLaundry.Models.User", b =>
                {
                    b.HasOne("LinkYourLaundry.Models.User", "GroupOwner")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupOwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
